In [30]:
#import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB


In [31]:
#import data
spam_df = pd.read_csv('spam.csv')

In [32]:
#inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [33]:
#turn spam/ham into numarical data, creating a new column called 'spam'
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [34]:
#create train/test split
x_train, x_test, y_train, y_test = train_test_split(spam_df.Message, spam_df.spam)

In [35]:
#find word count and store data as a matrix
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)


In [36]:
x_train_count

<4179x7489 sparse matrix of type '<class 'numpy.int64'>'
	with 55833 stored elements in Compressed Sparse Row format>

In [37]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [38]:
#train model
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [39]:
#pre test ham
email_ham = ["hey wanna meet up for the game ?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0])

In [40]:
#pre test spam
email_spam = ["reward monew click"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [41]:
#test model
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9842067480258435